version: '3'

services:
  ssl-vision-client:
    image: robocupssl/ssl-vision-client:1.6.0
    ports:
      - 8080:8082/tcp
    labels:
      - networks=bridge

  ssl-status-board:
    image: robocupssl/ssl-status-board:2.4.1
    ports:
      - 8082:8082/tcp
    labels:
      - networks=bridge

  ssl-game-controller:
    image: robocupssl/ssl-game-controller:2.12.7
    volumes:
      - ./ssl-game-controller/:/config:rw
    ports:
      - 8081:8081/tcp
      - 10007:10007/tcp
      - 10008:10008/tcp
      - 10011:10011/tcp
    labels:
      - networks=bridge

  ssl-auto-recorder:
    image: robocupssl/ssl-auto-recorder:0.2.2
    volumes:
      - ./ssl-auto-recorder/:/data:rw
    labels:
      - networks=bridge

  autoref-tigers:
    image: tigersmannheim/auto-referee:0.13.0-9-g3703023
    command: [ "-a" ]
    labels:
      - networks=bridge

  autoref-erforce:
    image: roboticserlangen/autoref:commit-e7313ef21be6
    labels:
      - networks=bridge

  connect-bridge:
    image: docker:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: /bin/sh -c 'sleep 5s; docker ps -f label=networks=bridge --format "{{.ID}}" | xargs -n1 docker network connect bridge'
